version: '3.3'

services:

#{{#if (eval sqlDatabase '==' 'postgres')}}
  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: demo-api
#{{/if}}
#{{#if (eval sqlDatabase '==' 'mysql')}}
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_ROOT_PASSWORD: pwd123
      MYSQL_DATABASE: demo-api
#{{/if}}
#{{#if (eval sqlDatabase '==' 'mariadb')}}
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: pwd123
      MARIADB_ROOT_PASSWORD: pwd123
      MARIADB_DATABASE: demo-api
#{{/if}}
#{{#if (eval sqlDatabase '==' 'mssql')}}
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pwd123
      - MSSQL_PID=Developer
  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "pwd123" -Q "create database demo-api"; do sleep 5; done'
#{{/if}}

#{{#if (eval authentication '==' 'keycloak-jwt')}}
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - 8403:8080
    volumes:
      - ./keycloak:/tmp
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/demo_realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: h2
#{{/if}}

#{{#if (eval 'jenkins 'in' features)}}
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    ports:
      - 8180:8080
    volumes:
      - ./keycloak:/tmp
    environment:
      KEYCLOAK_USER: admin
#{{/if}}

#{{#if (eval 'kafka 'in' 'features')}}
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#{{/if}}
