spring:
  jpa:
    hibernate:
      ddl-auto: none
#{{#if (eval sqlDatabase '==' 'mysql')}}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#{{/if}}
#{{#if (eval sqlDatabase '==' 'mysql')}}
    #!#database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#{{/if}}
#{{#if (eval sqlDatabase '==' 'mariadb')}}
    #!#database-platform: org.hibernate.dialect.MariaDB103Dialect
#{{/if}}
  datasource:
#{{#if (eval sqlDatabase '==' 'mysql')}}
    url: "jdbc:postgresql://localhost:5432/demo-api"
#{{/if}}
#{{#if (eval sqlDatabase '==' 'mysql')}}
    #!#url: "jdbc:mysql://localhost:3306/demo-api"
#{{/if}}
#{{#if (eval sqlDatabase '==' 'mariadb')}}
    #!#url: "jdbc:mariadb://localhost:3306/demo-api"
#{{/if}}
    username: dbuser
    password: pwd123
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
