spring:
  jpa:
    hibernate:
      ddl-auto: none
#{{ifX sqlDatabase '==' 'mysql'}}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#{{/ifX}}
#{{ifX sqlDatabase '==' 'mysql'}}
    #!#database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#{{/ifX}}
#{{ifX sqlDatabase '==' 'mariadb'}}
    #!#database-platform: org.hibernate.dialect.MariaDB103Dialect
#{{/ifX}}
  datasource:
#{{ifX sqlDatabase '==' 'mysql'}}
    url: "jdbc:postgresql://localhost:5432/demo-api"
#{{/ifX}}
#{{ifX sqlDatabase '==' 'mysql'}}
    #!#url: "jdbc:mysql://localhost:3306/demo-api"
#{{/ifX}}
#{{ifX sqlDatabase '==' 'mariadb'}}
    #!#url: "jdbc:mariadb://localhost:3306/demo-api"
#{{/ifX}}
    username: dbuser
    password: pwd123
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
